services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: users-admin-app:latest
    environment:
      NODE_ENV: production
      PORT: 3000
      # DATABASE_URL: postgres://postgres:postgres@db:5432/app_db
      DB_DIALECT: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: app_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      SESSION_SECRET: change_this_prod_secret
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${APP_PORT:-3000}:3000"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
