app = "users-admin-app"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  RUN_MIGRATIONS = "true"
  RUN_SEEDS = "true"
  HTTPS_ENABLED = "true"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0